/* Portfolio de Keise. Sem bibliotecas externas, rastreamento ou avaliação de código. */
(() => {
'use strict';
const projects = [
{id:'escritorio-360',n:'01',title:'Escritório em Ação 360°',type:'Simulação profissional',area:'Design de Interiores',img:'04',detail:'05',intro:'Um ambiente de trabalho como ponto de partida para explorar um briefing e tomar decisões de projeto.',context:'Aproximar conteúdos de Design de Interiores de uma situação profissional simulada, em que o estudante precisa considerar informações de um cliente antes de agir.',goal:'Exercitar a leitura de um briefing e a tomada de decisão em contexto, articulando as informações disponíveis às ações solicitadas na experiência.',solution:'O ambiente 360° reúne missão, briefing, cliente e objetos interativos. A exploração do espaço dá acesso às informações e às ações que organizam o percurso.',choices:[['Contexto antes da ação','A missão e o briefing situam o estudante: há uma demanda a compreender, não apenas um cenário para observar.'],['Objetos com função','Os elementos interativos integram a navegação ao ambiente profissional e dão acesso a etapas da experiência.'],['Decisão acompanhada','A sequência de ações e o feedback fazem parte da proposta de prática contextualizada.']],steps:[['Conhecer a missão','Entender a situação de atendimento apresentada.'],['Explorar o ambiente','Localizar o briefing e os objetos interativos.'],['Relacionar informações','Considerar a demanda do cliente nas decisões.'],['Avançar e conferir','Acompanhar a sequência de ações e o feedback.']],skills:['Roteirização de cenários','Organização do percurso','Simulação educacional','Design de interação'],record:'Telas do ambiente e do ponto de acesso à Prática 360°, acompanhadas da descrição da missão, do briefing e da intenção pedagógica.',tech:'Ambiente digital 360° e objetos interativos.'},
{id:'duvidas',n:'02',title:'Momento Responde Dúvidas',type:'Gamificação',area:'Atividades extensionistas',img:'03',intro:'Uma FAQ transformada em exploração: cada descoberta revela uma orientação para o estudante.',context:'Apresentar dúvidas recorrentes sobre atividades extensionistas em um formato que convide o estudante a explorar as orientações.',goal:'Favorecer o contato com orientações da atividade extensionista por meio de pequenas descobertas, mantendo a resposta vinculada à dúvida revelada.',solution:'Um jogo inspirado em brick breaker associa blocos a dúvidas. A progressão visual acompanha a descoberta, e um painel lateral apresenta as respostas.',choices:[['Conteúdo em pequenas unidades','As dúvidas organizam a informação em entradas delimitadas, em vez de um único texto extenso.'],['Resposta no contexto da descoberta','O painel lateral aproxima a interação da orientação que ela revela.'],['Percurso visível','A progressão sinaliza o que já foi explorado na experiência.']],steps:[['Entrar na dinâmica','Conhecer a proposta e os controles apresentados.'],['Explorar os blocos','Interagir com os elementos associados às dúvidas.'],['Ler a orientação','Consultar a resposta exibida no painel lateral.'],['Acompanhar a descoberta','Reconhecer o avanço pelas dúvidas disponíveis.']],skills:['Curadoria de orientações','Roteirização','Gamificação','Microinterações'],record:'Interface do jogo, painel de respostas e descrição da organização das dúvidas.',tech:'HTML, CSS e JavaScript.'},
{id:'triagem',n:'03',title:'Triagem das peças',type:'Aprender decidindo',area:'Design e sustentabilidade',img:'06',intro:'Conceitos de circularidade ganham uma tarefa: decidir o destino de componentes e conferir a classificação.',context:'Trabalhar circularidade para além de uma explicação textual, vinculando conceitos à análise e à classificação de componentes.',goal:'Relacionar as possibilidades de reuso, reparo, remanufatura, reciclagem e rejeito aos critérios de classificação apresentados na atividade.',solution:'A dinâmica coloca componentes em uma área de trabalho e propõe sua classificação entre diferentes destinos, com ação e conferência.',choices:[['Conceito convertido em critério','As categorias deixam de ser apenas definições e passam a orientar a decisão sobre cada componente.'],['Classificação como ação','A interação de arrastar e soltar materializa a escolha dentro da área de trabalho.'],['Conferência após a escolha','O feedback faz parte da proposta para que o estudante examine a classificação realizada.']],steps:[['Observar o componente','Examinar a peça e as informações apresentadas.'],['Considerar os destinos','Relacionar a peça às categorias disponíveis.'],['Classificar','Posicionar o componente no destino escolhido.'],['Conferir','Consultar a devolutiva e examinar a decisão.']],skills:['Design de atividades','Feedback','Interação aplicada a conceitos','Organização visual'],record:'Interface da atividade de triagem, categorias de destinação e descrição da proposta de classificação.',tech:'Interação de arrastar e soltar com conferência.'},
{id:'tours',n:'04',title:'Tours virtuais e negociação imobiliária',type:'Pesquisa e reflexão',area:'Mercado imobiliário',img:'01',intro:'Exploração visual, recorte de pesquisa e reflexão aplicada no mesmo percurso de aprendizagem.',context:'Articular exploração de conteúdo, evidência de pesquisa e reflexão sobre o uso de tours virtuais na negociação imobiliária.',goal:'Preparar o estudante para formular uma contribuição fundamentada nas informações exploradas, relacionando-as ao contexto imobiliário.',solution:'Um ambiente visual reúne cards de exploração, um recorte de pesquisa em apresentação jornalística, indicação de progresso e um espaço para a contribuição do estudante.',choices:[['Informação antes da pergunta','As descobertas precedem a reflexão para oferecer contexto à contribuição do estudante.'],['Curadoria em destaque','O recorte de pesquisa é integrado à experiência, em vez de aparecer como leitura desconectada do percurso.'],['Exploração que leva à elaboração','O espaço de contribuição faz a passagem entre consultar informações e construir uma resposta.']],steps:[['Explorar os conteúdos','Percorrer os cards apresentados no ambiente.'],['Consultar a pesquisa','Ler o recorte de evidência selecionado.'],['Relacionar ao contexto','Considerar as implicações para a negociação imobiliária.'],['Elaborar uma contribuição','Responder à proposta reflexiva a partir da exploração.']],skills:['Curadoria de conteúdo','Sequenciamento didático','Design de atividade reflexiva','Narrativa visual'],record:'Interface com cards, recorte de pesquisa e espaço de reflexão, além da descrição de sua organização pedagógica.',tech:'Ambiente visual interativo e registro de contribuição.'}
];
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TRIAGEM_IMAGE = 'assets/triagem-pecas-20260925.avif';
const TRIAGEM_ALT = 'Triagem das peças: componentes de uma cadeira sobre a bancada e cinco destinos coloridos — Reuso, Reparo, Remanufatura, Reciclagem e Rejeito.';
const picture = (number, alt) => `<img src="${esc(number==='06' ? TRIAGEM_IMAGE : window.KEISE_IMAGES?.[number] || `assets/imagem-${number}.webp`)}" alt="${esc(number==='06' ? TRIAGEM_ALT : alt)}" decoding="async">`;
// O catálogo apresenta imagens e estudos de caso, sem distribuir código ou acesso aos recursos.
function caseMarkup(p) {
 const next = projects[(projects.indexOf(p)+1)%projects.length];
 return `<nav class="breadcrumb" aria-label="Localização"><a href="#projetos">Projetos</a><span aria-hidden="true">/</span><span>${esc(p.type)}</span></nav><header class="case-heading"><p class="eyebrow">Estudo de caso ${p.n} · ${esc(p.area)}</p><h1 id="case-title" tabindex="-1">${esc(p.title)}</h1><p class="lead">${esc(p.intro)}</p><div class="actions"><a class="text-link" href="#revista">Conhecer a versão editorial →</a></div></header><figure class="case-visual"><button class="zoom" data-zoom aria-label="Ampliar a tela de ${esc(p.title)}">${picture(p.img,'Interface de '+p.title)}<span>Ampliar tela ↗</span></button><figcaption>Registro visual do recurso · ${esc(p.type)}</figcaption></figure><div class="case-columns"><div class="case-story"><section><p class="eyebrow">O ponto de partida</p><h2>Contexto de aprendizagem</h2><p>${esc(p.context)}</p></section><section><h2>Objetivo pedagógico</h2><p>${esc(p.goal)}</p></section><section><h2>Como a proposta se organiza</h2><p>${esc(p.solution)}</p></section></div><aside class="case-aside"><p class="eyebrow">O trabalho em foco</p><h2>Competências mobilizadas</h2><div class="skill-tags">${p.skills.map(s=>`<span>${esc(s)}</span>`).join('')}</div><h3>Recursos da experiência</h3><p>${esc(p.tech)}</p></aside></div><section class="case-section"><p class="eyebrow">Da intenção à interface</p><h2>Escolhas de design educacional</h2><div class="decisions">${p.choices.map(([t,d],i)=>`<div class="decision"><span class="number">0${i+1}</span><h3>${esc(t)}</h3><p>${esc(d)}</p></div>`).join('')}</div></section><section class="case-section journey"><div><p class="eyebrow">O estudante em atividade</p><h2>Percurso proposto</h2><p>Uma síntese da sequência de aprendizagem descrita neste caso.</p></div><ol>${p.steps.map(([t,d],i)=>`<li><span class="step-index">0${i+1}</span><div><h3>${esc(t)}</h3><p>${esc(d)}</p></div></li>`).join('')}</ol></section><section class="case-evidence"><div><p class="eyebrow">Documentação do caso</p><h2>O que está apresentado</h2><p>${esc(p.record)}</p><p class="evidence-note">Os objetivos descrevem a intenção pedagógica. Não são apresentados como resultados de aprendizagem mensurados.</p></div>${p.detail?picture(p.detail,'Detalhe do ponto de acesso à Prática 360°'):''}</section><nav class="case-next" aria-label="Continuar pelos projetos"><a class="text-link" href="#projetos">← Todos os projetos</a><a class="text-link" href="#${next.id}">Próximo: ${esc(next.title)} →</a></nav>`;
}
const views = [...document.querySelectorAll('[data-view]')];
const anchors = new Set(['projetos','atuacao','contato']);
const ids = new Set(['inicio','revista',...anchors,...projects.map(p=>p.id)]);
const frame = document.getElementById('magazine-frame');
let loadedMagazine=false, first=true;
function render() {
 let route; try { route=decodeURIComponent(location.hash.slice(1)); } catch (_) { route='inicio'; }
 if (!ids.has(route)) route='inicio';
 const project=projects.find(p=>p.id===route);
 const name=project?'caso':anchors.has(route)?'inicio':route;
 if(project) document.getElementById('case-content').innerHTML=caseMarkup(project);
 views.forEach(view=>{view.hidden=view.dataset.view!==name;view.classList.toggle('is-active',!view.hidden);});
 document.body.classList.toggle('in-magazine',name==='revista');
 document.title=project?project.title+' — Keise Pâmela Morais':'Design Educacional — Keise Pâmela Morais';
 document.querySelectorAll('.site-nav a').forEach(a=>{if(a.hash==='#'+route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 if(name==='revista'&&!loadedMagazine){loadedMagazine=true;loadMagazine();}
 requestAnimationFrame(()=>{
  if(anchors.has(route)){const section=document.getElementById(route);section.scrollIntoView({behavior:'instant'});section.querySelector('h2').focus({preventScroll:true});}
  else{window.scrollTo({top:0,behavior:'instant'});if(!first)document.querySelector('[data-view="'+name+'"] h1')?.focus({preventScroll:true});}
  first=false;
 });
}
window.addEventListener('hashchange',render);
const dialog=document.getElementById('image-dialog'), dialogImage=document.getElementById('dialog-image');
document.addEventListener('click',e=>{
 if(e.target.closest('.skip-link')){e.preventDefault();document.getElementById('conteudo').focus();return;}
 const zoom=e.target.closest('[data-zoom]');if(!zoom)return;
 const img=zoom.querySelector('img');dialogImage.src=img.currentSrc||img.src;dialogImage.alt=img.alt;
 document.getElementById('dialog-title').textContent=img.alt;dialog.showModal();document.body.classList.add('modal-open');
});
document.getElementById('close-dialog').onclick=()=>dialog.close();
dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');dialogImage.removeAttribute('src');});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});

// The immutable original supplies only CSS and static page templates. Its script is never executed.
async function loadMagazine() {
 const status=document.getElementById('magazine-status');
 try {
  let source=window.KEISE_ORIGINAL;
  if(typeof source!=='string'){const res=await fetch('revista-base.html');if(!res.ok)throw new Error('HTTP '+res.status);source=await res.text();}
  // Atualiza a captura na revista sem modificar os demais projetos.
  source=source.replaceAll('assets/imagem-06.webp',TRIAGEM_IMAGE);
  const parsed=new DOMParser().parseFromString(source,'text/html');
  const match=source.match(/const pages = \[([\s\S]*?)\n\];/);
  if(!match)throw new Error('A estrutura da revista não foi encontrada.');
  const pages=[...match[1].matchAll(/`([\s\S]*?)`/g)].map(m=>m[1]);
  if(pages.length!==12)throw new Error('A contagem de páginas da revista mudou.');
  const casePages={2:'duvidas',4:'escritorio-360',6:'triagem',8:'tours'};
  Object.entries(casePages).forEach(([i,id])=>{pages[i]=pages[i].replace('</div><span class="page-no">',`<button class="case-more" data-case="${id}">Ver decisões pedagógicas →</button></div><span class="page-no">`);});
  pages[2]=pages[2].replace('com 17 dúvidas','com dúvidas organizadas');pages[4]=pages[4].replace('profissional real.','profissional simulada.');
  const css=[...parsed.querySelectorAll('style')].map(s=>s.textContent).join('\n');
  const fix=`
.btn{min-height:44px}:focus-visible{outline:3px solid #59408b;outline-offset:4px}#leaf{pointer-events:none}.page{overflow:auto}.copy{height:auto;min-height:100%;padding-bottom:45px}.half{overflow:auto}.case-more{align-self:flex-start;margin-top:16px;padding:10px 15px;border:1px solid #bca4d5;border-radius:30px;background:#f5effc;color:#52326f;font:700 .9rem/1.4 system-ui;cursor:pointer}#count{font-size:.82rem;min-width:65px;text-align:center}#chapter{max-width:185px}
@media(max-width:900px){html,body{height:100%;height:100dvh;overflow:hidden}.app{height:100%;grid-template-rows:auto minmax(0,1fr) auto;padding:8px;gap:8px}.bar{flex-wrap:wrap;justify-content:center;gap:6px}.brand{font-size:.88rem;flex-wrap:wrap;justify-content:center;gap:6px}.brand>span:last-child{display:none}.controls{justify-content:center;gap:5px}.btn{font-size:.78rem;padding:8px 11px}.stage{min-height:0;overflow:hidden}.magazine{width:100%;height:100%;min-height:0;perspective:none}.magazine::after,.magazine::before,.spread::after{display:none}.spread{border-radius:18px;grid-template-columns:minmax(0,1fr)}.half.left{display:none}.half.right{display:block;overflow:auto;min-height:0;box-shadow:none}.half.right .page{height:100%;overflow-y:auto;overscroll-behavior:contain;touch-action:pan-y}.copy{padding:25px 24px 48px;height:auto;min-height:100%}.copy h2{font-size:clamp(1.9rem,8vw,2.6rem);line-height:1.05}.copy p{font-size:1rem;line-height:1.6}.chips{gap:6px}.chip{font-size:.8rem}.about-thinking-inner{min-height:100%;height:auto;overflow:visible!important;grid-template-columns:1fr;padding:25px 24px 48px!important}.about-intro p{font-size:.94rem!important;line-height:1.6!important}.thinking-cards span{font-size:.85rem!important;line-height:1.5!important}.thinking-cards b{font-size:.95rem!important}.keise-cover{min-height:100%;height:auto;grid-template-columns:1fr!important;grid-template-rows:auto auto!important;gap:12px;padding:26px 24px 45px!important}.keise-copy{padding:0!important}.keise-copy h1{font-size:2.45rem!important;line-height:1.02!important}.keise-copy p{font-size:.95rem!important;line-height:1.55!important}.keise-portrait-zone{min-height:270px!important;height:300px!important}.keise-photo-frame{max-width:220px!important;height:260px!important;margin:auto}.keise-note{font-size:.78rem!important}.contact h2{font-size:2.4rem}.contact{min-height:100%;height:auto;padding-bottom:48px}.photo{min-height:100%;height:auto;position:relative}.photo>img{max-height:70vh;height:auto}.page-no{bottom:10px}.progress,.hint{display:none}footer.bar .controls{flex-wrap:nowrap;gap:5px;width:100%;justify-content:center}footer.bar .btn{font-size:.72rem;padding:8px 10px}#chapter{max-width:110px}#count{min-width:43px;font-size:.75rem}}
@media(max-width:370px){footer.bar .btn{padding:7px 8px;font-size:.68rem}#chapter{max-width:96px}#count{min-width:38px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
`;
  const body=`<div class="app"><header class="bar"><div class="brand"><span class="dot"></span>Keise Pâmela Morais<span>· Design Educacional</span></div><div class="controls"><button class="btn" id="reading">Leitura direta</button><button class="btn" id="sound" aria-pressed="true">🔊 Som ligado</button><button class="btn" id="full">⛶ Tela cheia</button></div></header><main class="stage"><section class="magazine" id="magazine" aria-label="Portfólio em revista"><div class="spread"><div class="half left" id="leftPage"></div><div class="half right" id="rightPage"></div></div><div class="leaf" id="leaf" aria-hidden="true" inert><div class="leaf-face leaf-front" id="leafFront"></div><div class="leaf-face leaf-back" id="leafBack"></div></div></section></main><footer class="bar"><span class="hint">Arraste a folha ou use as setas ← →</span><div class="progress"><span id="prog"></span></div><div class="controls"><button class="btn" id="prev">← Anterior</button><select class="btn" id="chapter" aria-label="Ir para uma seção"><option value="0">Capa</option><option value="1">Sobre mim</option><option value="2">Responde Dúvidas</option><option value="4">Escritório 360°</option><option value="6">Triagem das peças</option><option value="8">Tours virtuais</option><option value="10">Contato</option></select><span id="count" aria-live="polite" aria-atomic="true"></span><button class="btn" id="next">Próxima →</button></div></footer></div>`;
  frame.onload=()=>{frame.onload=null;setupMagazine(frame.contentDocument,pages);status.hidden=true;};
  frame.srcdoc='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revista · Keise</title><style>'+css+fix+'</style></head><body>'+body+'</body></html>';
 } catch(error) {loadedMagazine=false;status.hidden=false;status.textContent='Não foi possível abrir a revista. A leitura direta continua disponível.';console.error(error);}
}
function setupMagazine(d,pages) {
 const get=id=>d.getElementById(id), left=get('leftPage'),right=get('rightPage'),leaf=get('leaf'),lf=get('leafFront'),lb=get('leafBack'),mag=get('magazine');
 const compact=d.defaultView.matchMedia('(max-width:900px)'),reduced=d.defaultView.matchMedia('(prefers-reduced-motion:reduce)');
 let page=0,busy=false,soundOn=true,mode='next',timer,dragging=false,startX=0,startY=0,lastX=0,lastT=0,velocity=0,turn=0,audio;
 function draw(){if(!compact.matches)page=Math.floor(page/2)*2;left.innerHTML=compact.matches?'':pages[page];right.innerHTML=pages[page+(compact.matches?0:1)]||'';const last=Math.min(page+(compact.matches?1:2),12);get('count').textContent=compact.matches?`${page+1} / 12`:`${page+1}–${last} / 12`;get('prog').style.width=last/12*100+'%';get('prev').disabled=page===0;get('next').disabled=last>=12;get('chapter').value=String([0,1,2,4,6,8,10].filter(v=>v<=page).pop()||0);d.querySelectorAll('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer');}
 function rustle(){if(!soundOn)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;audio=audio||new C();audio.resume().catch(()=>{});const len=Math.floor(audio.sampleRate*.33),buffer=audio.createBuffer(1,len,audio.sampleRate),data=buffer.getChannelData(0);let smooth=0;for(let i=0;i<len;i++){const t=i/len;smooth=smooth*.6+(Math.random()*2-1)*.4;data[i]=smooth*Math.min(1,t/.08)*Math.pow(1-t,1.35)*(.78+.22*Math.sin(t*11*Math.PI));}const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=2200;gain.gain.value=.06;source.connect(filter).connect(gain).connect(audio.destination);source.start();}
 function curl(t,y=0){turn=Math.max(0,Math.min(1,t));const arc=Math.sin(Math.PI*turn),eased=turn<.5?2*turn*turn:1-Math.pow(-2*turn+2,2)/2;leaf.style.setProperty('--turn',turn);leaf.style.setProperty('--curl',arc*66+'px');leaf.style.setProperty('--tilt',Math.max(-2.2,Math.min(2.2,y*2.2))+'deg');leaf.style.transform=`rotateY(${mode==='next'?-180*eased:-180*(1-eased)}deg) translateZ(${arc*58}px) translateY(${arc*Math.max(-12,Math.min(12,y*12))}px) scaleX(${1-arc*.012})`;}
 function prepare(which){if(busy)return false;mode=which;if(which==='next'){if(page+2>=12)return false;lf.innerHTML=pages[page+1];lb.innerHTML=pages[page+2];leaf.style.left='50%';leaf.style.transformOrigin='left center';}else{if(page<=0)return false;lf.innerHTML=pages[page-1];lb.innerHTML=pages[page];leaf.style.left='0';leaf.style.transformOrigin='right center';}busy=true;leaf.classList.remove('soft');leaf.classList.add('active');curl(0);return true;}
 function settle(commit){leaf.style.transition='';leaf.classList.add('soft');curl(commit?1:0);if(commit)rustle();timer=setTimeout(()=>{if(commit)page+=mode==='next'?2:-2;leaf.classList.remove('active','soft');leaf.style.transform='';busy=false;draw();},820);}
 function go(which){if(busy)return;if(compact.matches||reduced.matches){const target=page+(which==='next'?1:-1)*(compact.matches?1:2);if(target<0||target>=12)return;page=target;draw();rustle();}else if(prepare(which))requestAnimationFrame(()=>settle(true));}
 get('prev').onclick=()=>go('prev');get('next').onclick=()=>go('next');get('chapter').onchange=e=>{if(busy)return;page=Number(e.target.value);draw();};
 get('reading').onclick=()=>location.hash='inicio';get('sound').onclick=()=>{soundOn=!soundOn;get('sound').textContent=soundOn?'🔊 Som ligado':'🔇 Som desligado';get('sound').setAttribute('aria-pressed',String(soundOn));if(soundOn)rustle();};
 get('full').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch(_){}};
 d.addEventListener('click',e=>{const button=e.target.closest('[data-case]');if(button)location.hash=button.dataset.case;});
 d.addEventListener('keydown',e=>{if(e.target.closest('a,button,select,input,textarea')||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'){e.preventDefault();go('next');}if(e.key==='ArrowLeft'){e.preventDefault();go('prev');}});
 compact.addEventListener('change',()=>{clearTimeout(timer);busy=false;dragging=false;leaf.classList.remove('active','soft');leaf.style.transform='';leaf.style.transition='';draw();});
 mag.addEventListener('pointerdown',e=>{if(compact.matches||reduced.matches||busy||e.button!==0||e.target.closest('a,button,select,input,textarea'))return;const r=mag.getBoundingClientRect();if(!prepare(e.clientX-r.left>r.width/2?'next':'prev'))return;dragging=true;startX=lastX=e.clientX;startY=e.clientY;lastT=performance.now();velocity=0;leaf.style.transition='none';mag.setPointerCapture?.(e.pointerId);});
 mag.addEventListener('pointermove',e=>{if(!dragging)return;const r=mag.getBoundingClientRect(),now=performance.now();velocity=(e.clientX-lastX)/Math.max(8,now-lastT);lastX=e.clientX;lastT=now;curl((mode==='next'?startX-e.clientX:e.clientX-startX)/(r.width*.48),(e.clientY-startY)/(r.height*.55));});
 const release=()=>{if(!dragging)return;dragging=false;settle(turn>.31||(mode==='next'?velocity<-.38:velocity>.38));};mag.addEventListener('pointerup',release);mag.addEventListener('pointercancel',()=>{if(dragging){dragging=false;settle(false);}});
 draw();
}
render();
})();
