/* Conteúdo herdado do HTML v19.7: IDs, oito componentes, gabarito e 10 pontos por peça.
 * Os encaminhamentos são critérios deste caso didático, não diagnósticos de objetos reais.
 */
'use strict';
const MC_CONTENT={
 version:'21.0',gameId:'missao-circular',maxPoints:80,
 categories:[
  {id:'reuse',name:'Reuso',color:'#368fcb',light:'#e6f2fa',icon:'reuse',summary:'Usar novamente, sem reconstruir.',description:'O componente está íntegro e pode voltar ao uso nas condições apresentadas neste caso.'},
  {id:'repair',name:'Reparo',color:'#619d45',light:'#edf5e7',icon:'tool',summary:'Corrigir um dano localizado.',description:'Uma intervenção localizada permite recuperar a função ou a superfície preservando a estrutura.'},
  {id:'reman',name:'Remanufatura',color:'#e5b228',light:'#fff7da',icon:'gear',summary:'Reconstruir e testar o conjunto.',description:'O caso prevê recuperação técnica mais abrangente do conjunto, com reconstrução e testes.'},
  {id:'recycle',name:'Reciclagem',color:'#e87932',light:'#fff0e6',icon:'recycle',summary:'Recuperar o material.',description:'Sem uso como componente nas condições do caso, o material é encaminhado para transformação.'},
  {id:'reject',name:'Rejeito',color:'#cf565b',light:'#fdeced',icon:'bin',summary:'Destinar sem recuperação viável.',description:'Neste cenário didático, não foi disponibilizada uma rota viável de recuperação para esta peça.'}
 ],
 parts:[
  {id:'seat',n:1,name:'Assento estofado',material:'Revestimento têxtil, espuma e estrutura',destination:'repair',newText:'Revestimento contínuo, costuras fechadas e apoio sem deformação aparente.',observation:'Há um rasgo no revestimento e espuma exposta. A estrutura de apoio permanece íntegra.',detail:'A abertura está na região frontal direita. Gire a peça e compare o tecido danificado com a estrutura preservada.',reason:'O assento mantém estrutura aproveitável e pode receber novo revestimento e espuma.',hint:'Diferencie o dano do revestimento do estado da estrutura que o sustenta.',test:'Ver a área desgastada'},
  {id:'back',n:2,name:'Encosto estofado',material:'Revestimento, espuma e conjunto de suporte',destination:'reman',newText:'Superfície íntegra, enchimento regular e suporte alinhado.',observation:'Desgaste extenso, perda de enchimento e danos no conjunto do encosto. A avaliação do caso prevê sua reconstrução.',detail:'Examine a superfície e a parte traseira. A recuperação envolve mais do que um reparo localizado no tecido.',reason:'O encosto exige reconstrução mais ampla do conjunto, adequada à remanufatura.',hint:'O problema envolve o conjunto, e não apenas um pequeno acabamento.',test:'Examinar o suporte'},
  {id:'armL',n:3,name:'Braço esquerdo',material:'Apoio e suporte de ligação',destination:'reuse',newText:'Apoio sem trincas, bordas contínuas e ligação estável.',observation:'O braço está íntegro. Não há trinca ou perda de função descrita no caso.',detail:'Compare com o braço direito. Uma cadeira desgastada pode conter componentes ainda utilizáveis.',reason:'O braço esquerdo está íntegro e pode ser reutilizado diretamente.',hint:'Observe se há realmente algum comprometimento da função.',test:'Testar estabilidade'},
  {id:'armR',n:4,name:'Braço direito',material:'Material identificado para reciclagem no caso',destination:'recycle',newText:'Apoio inteiro, sem abertura ou fratura na extremidade.',observation:'Há uma trinca e separação na extremidade do apoio. O caso prevê recuperação do material, não do componente.',detail:'A fratura aparece como uma abertura real no modelo. O material tem rota de reciclagem prevista neste cenário.',reason:'O braço direito está trincado; seu material pode seguir para reciclagem.',hint:'Diferencie recuperar a função da peça e recuperar seu material.',test:'Examinar a trinca'},
  {id:'base',n:5,name:'Base metálica',material:'Metal com acabamento superficial',destination:'repair',newText:'Estrutura contínua e acabamento uniforme, sem oxidação aparente.',observation:'Há oxidação superficial. Os cinco apoios continuam inteiros no caso.',detail:'Observe as áreas de oxidação sem confundi-las com uma ruptura da estrutura.',reason:'A base metálica está inteira e pode ser recuperada por limpeza e tratamento da oxidação.',hint:'A aparência desgastada não implica necessariamente perda da estrutura.',test:'Examinar a superfície'},
  {id:'piston',n:6,name:'Coluna / pistão',material:'Conjunto mecânico',destination:'reman',newText:'A coluna mantém a posição no teste virtual.',observation:'A falha é funcional: o pistão não sustenta a posição no teste virtual. Não basta examinar sua aparência.',detail:'O teste virtual mostra a perda de sustentação. Não abra nem tente reparar um pistão real: aqui, a inspeção é apenas uma simulação.',reason:'O pistão apresenta falha funcional e precisa de recuperação industrial.',hint:'Aqui é necessário considerar a função, além da superfície.',test:'Testar sustentação'},
  {id:'caster',n:7,name:'Rodízio',material:'Conjunto com roda e suporte',destination:'reject',newText:'Roda completa, sem perda de material, com movimento regular.',observation:'Uma parte da roda está ausente. Não há recuperação viável disponibilizada para esse conjunto nesta atividade.',detail:'Gire o rodízio para ver a parte que falta. A classificação considera as condições deste caso, não todo rodízio descartado.',reason:'O rodízio perdeu parte da roda e não oferece uso seguro ou recuperação viável nesta atividade.',hint:'Considere o dano e as rotas de recuperação efetivamente disponíveis no caso.',test:'Testar movimento'},
  {id:'screws',n:8,name:'Parafusos e conectores',material:'Fixadores metálicos',destination:'reuse',newText:'Fixadores completos, com cabeças e roscas preservadas.',observation:'Os fixadores estão íntegros, sem dano descrito que impeça seu aproveitamento.',detail:'O grupo é contabilizado como um dos oito componentes da atividade, assim como na versão original.',reason:'Os parafusos estão íntegros e podem ser reutilizados.',hint:'Estar separado do produto não significa estar danificado.',test:'Examinar os detalhes'}
 ],
 story:'A cadeira foi usada durante anos em uma empresa. Primeiro, era nova, completa e funcional. Com o uso contínuo e a manutenção adiada, surgiram rasgos, oxidação e falhas. Durante uma reforma, ela foi retirada inteira, embora vários componentes ainda tivessem valor. Observe a cadeira nova, compare com o estado após o uso e examine cada componente antes de decidir seu destino.',
 phases:[
  {id:'new',label:'Conheça a cadeira',short:'Conheça',title:'Cadeira nova.',subtitle:'Antes do uso',text:'Conheça o produto antes do desgaste. Gire, aproxime e selecione seus componentes.',next:'Observar o desgaste'},
  {id:'worn',label:'Observe o desgaste',short:'Observe',title:'O que mudou?',subtitle:'Após o uso',text:'A mesma cadeira, depois de anos de uso. Observe os danos e investigue o que ainda permanece íntegro.',next:'Desmontar virtualmente'},
  {id:'disassembly',label:'Desmonte e analise',short:'Analise',title:'Cada peça importa.',subtitle:'Desmontagem virtual',text:'Acompanhe a separação dos componentes e examine seus detalhes. Os danos permanecem nas mesmas peças.',next:'Ir para a triagem'},
  {id:'triage',label:'Faça a triagem',short:'Decida',title:'Triagem das peças.',subtitle:'Triagem das peças',text:'Examine as oito peças e escolha seu próximo destino. Considere a condição de cada componente e as possibilidades deste caso.',next:'Conferir triagem'},
  {id:'results',label:'Veja suas decisões',short:'Reflita',title:'Decisões que fazem diferença.',subtitle:'Resultado da missão',text:'Compare suas escolhas com os critérios do caso e retome o que merece uma nova análise.',next:'Concluir experiência'}
 ]
};
const MC_ICONS={
 arrow:'<path d="M4 12h15m-5-5 5 5-5 5"/>',back:'<path d="M20 12H5m5-5-5 5 5 5"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',check:'<path d="m5 12 4 4L19 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',
 leaf:'<path d="M20 3c-8-1-16 3-16 10 0 4 3 6 6 5 7-1 9-8 10-15Z"/><path d="M3 21 16 8M9 15l-1-5m1 5 5 1"/>',
 reuse:'<path d="M20 7a9 9 0 0 0-15-2L2 8m0-5v5h5M4 17a9 9 0 0 0 15 2l3-3m0 5v-5h-5"/>',
 recycle:'<path d="m9 5 3-4 4 6m-6-1 6 1 1-5M19 10l4 5-5 5m1-6-1 6h5M9 21H3l-2-6m6 3-6-3-1 6M3 12l3-5"/>',
 tool:'<path d="M14 3a6 6 0 0 0-6 8L2 17a3 3 0 0 0 5 5l6-7a6 6 0 0 0 8-7l-4 4-4-4 4-4-3-1Z"/>',
 gear:'<path d="m9 3 1-2h4l1 2 2 1 3 0 2 3-1 2v4l1 2-2 3h-3l-2 1-1 3h-4l-1-3-2-1H4l-2-3 1-2V9L2 7l2-3h3Z"/><circle cx="12" cy="11" r="3"/>',
 bin:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 9v9m4-9v9"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',
 zoom:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6M7 10h6m-3-3v6"/>',minus:'<path d="M5 12h14"/>',plus:'<path d="M5 12h14M12 5v14"/>',rotate:'<path d="M3 10a9 9 0 1 1 2 9M3 4v6h6"/>',
 sound:'<path d="M3 9h4l5-5v16l-5-5H3Zm13-1a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',mute:'<path d="M3 9h4l5-5v16l-5-5H3Zm13 0 6 6m0-6-6 6"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',bulb:'<path d="M8 17c0-4-3-4-3-8a7 7 0 0 1 14 0c0 4-3 4-3 8ZM9 20h6m-5 3h4"/>',
 book:'<path d="M12 5v16M12 5C8 2 4 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-2-1-6-2-10 1Z"/>',
 access:'<circle cx="12" cy="3" r="2"/><path d="M3 8h18M12 6v7m0 0-5 9m5-9 5 9"/>',expand:'<path d="M3 9V3h6m6 0h6v6m0 6v6h-6M9 21H3v-6"/>',download:'<path d="M12 2v13m-5-5 5 5 5-5M3 17v5h18v-5"/>',star:'<path d="m12 2 3 7 7 1-5 5 1 7-6-4-6 4 1-7-5-5 7-1Z"/>',mouse:'<rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 2v6"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h1m-1 6h1m-1 6h1"/>'
};
function icon(id,cls=''){return `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${MC_ICONS[id]||MC_ICONS.info}</svg>`}
function logo(){return `<svg class="brand-mark" viewBox="0 0 72 72" fill="none" aria-hidden="true"><path d="M55 16a28 28 0 0 1 2 40" stroke="#246b59" stroke-width="6"/><path d="m57 45 2 13-12-1" fill="#246b59"/><path d="M17 56A28 28 0 0 1 19 13" stroke="#77a392" stroke-width="6"/><path d="m14 10 13 2-5 11" fill="#77a392"/><path d="M25 48C17 34 33 26 46 20c3 19-4 31-21 28Z" fill="#9aab56"/><path d="m23 55 16-25" stroke="#fff" stroke-width="2"/><path d="M23 48c-9 0-14-8-15-15 10 1 18 5 15 15Z" fill="#657b36"/></svg>`}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
