/* Missão Circular — renderizador WebGL2 local, sem bibliotecas ou recursos remotos.
 * Revisão do jogo v19.7. Geometrias procedurais, iluminação, sombras e seleção real.
 */
'use strict';
const MC3D=(()=>{
 const V={add:(a,b)=>a.map((v,i)=>v+b[i]),sub:(a,b)=>a.map((v,i)=>v-b[i]),mul:(a,s)=>a.map(v=>v*s),dot:(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{const n=Math.hypot(...a)||1;return a.map(v=>v/n)}};
 const identity=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
 function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
 function compose(p,r,s){const [x,y,z]=r,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);
  const m=identity();m[0]=cy*cz*s[0];m[1]=(cx*sz+sx*sy*cz)*s[0];m[2]=(sx*sz-cx*sy*cz)*s[0];m[4]=-cy*sz*s[1];m[5]=(cx*cz-sx*sy*sz)*s[1];m[6]=(sx*cz+cx*sy*sz)*s[1];m[8]=sy*s[2];m[9]=-sx*cy*s[2];m[10]=cx*cy*s[2];m[12]=p[0];m[13]=p[1];m[14]=p[2];return m;
 }
 function look(eye,target,up=[0,1,0]){const z=V.norm(V.sub(eye,target)),x=V.norm(V.cross(up,z)),y=V.cross(z,x),m=identity();m[0]=x[0];m[4]=x[1];m[8]=x[2];m[1]=y[0];m[5]=y[1];m[9]=y[2];m[2]=z[0];m[6]=z[1];m[10]=z[2];m[12]=-V.dot(x,eye);m[13]=-V.dot(y,eye);m[14]=-V.dot(z,eye);return m}
 function perspective(fov,aspect,near=.1,far=120){const f=1/Math.tan(fov/2),m=new Float32Array(16);m[0]=f/aspect;m[5]=f;m[10]=(far+near)/(near-far);m[11]=-1;m[14]=2*far*near/(near-far);return m}
 function ortho(l,r,b,t,n,f){const m=identity();m[0]=2/(r-l);m[5]=2/(t-b);m[10]=-2/(f-n);m[12]=-(r+l)/(r-l);m[13]=-(t+b)/(t-b);m[14]=-(f+n)/(f-n);return m}
 function transform(m,p){const x=p[0],y=p[1],z=p[2],w=m[3]*x+m[7]*y+m[11]*z+m[15];return[(m[0]*x+m[4]*y+m[8]*z+m[12])/w,(m[1]*x+m[5]*y+m[9]*z+m[13])/w,(m[2]*x+m[6]*y+m[10]*z+m[14])/w]}
 class Node{constructor(geo=null,mat=null){this.geo=geo;this.mat=mat;this.p=[0,0,0];this.r=[0,0,0];this.s=[1,1,1];this.children=[];this.visible=true;this.pickId=0;this.cast=true;this.world=identity();this.name='';}add(...nodes){this.children.push(...nodes);return this}clone(){const n=new Node(this.geo,this.mat);Object.assign(n,{p:[...this.p],r:[...this.r],s:[...this.s],visible:this.visible,pickId:this.pickId,cast:this.cast,name:this.name});n.children=this.children.map(c=>c.clone());return n}}
 const geom=(p,n,u,idx)=>{for(let j=0;j<idx.length;j+=3){const a=idx[j]*3,b=idx[j+1]*3,c=idx[j+2]*3,ab=[p[b]-p[a],p[b+1]-p[a+1],p[b+2]-p[a+2]],ac=[p[c]-p[a],p[c+1]-p[a+1],p[c+2]-p[a+2]],cross=V.cross(ab,ac),nn=[0,1,2].map(k=>n[a+k]+n[b+k]+n[c+k]);if(V.dot(cross,nn)<0)[idx[j+1],idx[j+2]]=[idx[j+2],idx[j+1]];}return{p:new Float32Array(p),n:new Float32Array(n),u:new Float32Array(u),idx:new Uint32Array(idx)}};
 function roundedBox(w,h,d,r=.08,segments=6){const p=[],n=[],uv=[],idx=[],dims=[w/2,h/2,d/2];r=Math.min(r,...dims);const faces=[[0,1,2,1],[0,1,2,-1],[1,2,0,1],[1,2,0,-1],[2,0,1,1],[2,0,1,-1]];
  faces.forEach(([axis,a,b,sign])=>{const start=p.length/3;for(let j=0;j<=segments;j++)for(let i=0;i<=segments;i++){let q=[0,0,0];q[axis]=dims[axis]*sign;q[a]=((i/segments)*2-1)*dims[a];q[b]=((j/segments)*2-1)*dims[b];const inner=q.map((v,k)=>Math.max(-dims[k]+r,Math.min(dims[k]-r,v)));let nn=r<.000001?[axis===0?sign:0,axis===1?sign:0,axis===2?sign:0]:V.norm(V.sub(q,inner));q=V.add(inner,V.mul(nn,r));p.push(...q);n.push(...nn);uv.push(i/segments,j/segments)}for(let j=0;j<segments;j++)for(let i=0;i<segments;i++){let v=start+j*(segments+1)+i;const cross=V.cross([axis===0?0: a===0?1:0,axis===1?0:a===1?1:0,axis===2?0:a===2?1:0],[b===0?1:0,b===1?1:0,b===2?1:0]);if(cross[axis]*sign>0)idx.push(v,v+1,v+segments+2,v,v+segments+2,v+segments+1);else idx.push(v,v+segments+2,v+1,v,v+segments+1,v+segments+2)}});return geom(p,n,uv,idx)}
 // Bordas arredondadas no plano da almofada, independentes da espessura.
 function slab(w,h,d,r=.3){const p=[],n=[],u=[],idx=[],N=48;const rings=[{f:.90,y:-h/2,ny:-1,nr:0},{f:.99,y:-h*.28,ny:-.6,nr:.8},{f:1,y:0,ny:0,nr:1},{f:.99,y:h*.26,ny:.6,nr:.8},{f:.91,y:h/2,ny:1,nr:0}];
  for(const ring of rings)for(let i=0;i<N;i++){const a=i/N*Math.PI*2+.00001,cs=Math.cos(a),sn=Math.sin(a),x=(Math.sign(cs)*(w/2-r)+cs*r)*ring.f,z=(Math.sign(sn)*(d/2-r)+sn*r)*ring.f;p.push(x,ring.y,z);n.push(cs*ring.nr,ring.ny,sn*ring.nr);u.push(x/w+.5,z/d+.5)}
  for(let j=0;j<rings.length-1;j++)for(let i=0;i<N;i++){const a=j*N+i,b=j*N+(i+1)%N,c=b+N,d0=a+N;idx.push(a,b,c,a,c,d0)}
  for(const [j,y,ny]of[[0,-h/2,-1],[rings.length-1,h/2,1]]){const o=p.length/3;p.push(0,y,0);n.push(0,ny,0);u.push(.5,.5);for(let i=0;i<N;i++){const a=j*N+i,b=j*N+(i+1)%N;ny>0?idx.push(o,b,a):idx.push(o,a,b)}}return geom(p,n,u,idx)
 }
 function cylinder(rt,rb,h,segs=40,arc=Math.PI*2,start=0){const p=[],n=[],u=[],idx=[];for(let j=0;j<=1;j++)for(let i=0;i<=segs;i++){const a=start+i/segs*arc,r=j?rt:rb,nn=V.norm([Math.sin(a),(rb-rt)/h,Math.cos(a)]);p.push(Math.sin(a)*r,(j-.5)*h,Math.cos(a)*r);n.push(...nn);u.push(i/segs,j)}for(let i=0;i<segs;i++)idx.push(i,i+segs+2,i+1,i,i+segs+1,i+segs+2);
  [0,1].forEach(j=>{let c=p.length/3,rad=j?rt:rb;p.push(0,(j-.5)*h,0);n.push(0,j?1:-1,0);u.push(.5,.5);for(let i=0;i<=segs;i++){const a=start+i/segs*arc;p.push(Math.sin(a)*rad,(j-.5)*h,Math.cos(a)*rad);n.push(0,j?1:-1,0);u.push(.5+Math.sin(a)*.5,.5+Math.cos(a)*.5);if(i)j?idx.push(c,c+i+1,c+i):idx.push(c,c+i,c+i+1)}});
  if(arc<Math.PI*2-.001){[start,start+arc].forEach((a,k)=>{const off=p.length/3;const nn=k?[-Math.cos(a),0,Math.sin(a)]:[Math.cos(a),0,-Math.sin(a)];[[0,-h/2,0],[Math.sin(a)*rb,-h/2,Math.cos(a)*rb],[Math.sin(a)*rt,h/2,Math.cos(a)*rt],[0,h/2,0]].forEach((v,i)=>{p.push(...v);n.push(...nn);u.push(i%2,Math.floor(i/2))});idx.push(off,off+1,off+2,off,off+2,off+3)})}return geom(p,n,u,idx)}
 function sphere(rx,ry=rx,rz=rx,segs=24,rings=16){const p=[],n=[],uv=[],idx=[];for(let j=0;j<=rings;j++)for(let i=0;i<=segs;i++){const t=j/rings*Math.PI,a=i/segs*Math.PI*2,nn=[Math.sin(t)*Math.sin(a),Math.cos(t),Math.sin(t)*Math.cos(a)];p.push(nn[0]*rx,nn[1]*ry,nn[2]*rz);n.push(...V.norm([nn[0]/rx,nn[1]/ry,nn[2]/rz]));uv.push(i/segs,j/rings)}for(let j=0;j<rings;j++)for(let i=0;i<segs;i++){const a=j*(segs+1)+i;idx.push(a,a+1,a+segs+2,a,a+segs+2,a+segs+1)}return geom(p,n,uv,idx)}
 function plane(w,d){const nx=Math.max(1,Math.ceil(w/1.2)),nz=Math.max(1,Math.ceil(d/1.2)),p=[],n=[],u=[],idx=[];for(let z=0;z<=nz;z++)for(let x=0;x<=nx;x++){p.push((x/nx-.5)*w,0,(z/nz-.5)*d);n.push(0,1,0);u.push(x/nx,z/nz);}for(let z=0;z<nz;z++)for(let x=0;x<nx;x++){const i=z*(nx+1)+x;idx.push(i,i+nx+2,i+1,i,i+nx+1,i+nx+2);}return geom(p,n,u,idx)}
 function polygon(points){const p=[0,0,0],n=[0,1,0],u=[.5,.5],idx=[];points.forEach(v=>{p.push(v[0],v[1]||0,v[2]);n.push(0,1,0);u.push(v[0]+.5,v[2]+.5)});for(let i=0;i<points.length;i++)idx.push(0,1+(i+1)%points.length,1+i);return geom(p,n,u,idx)}
 function color(hex){if(Array.isArray(hex))return hex;hex=hex.replace('#','');return[0,2,4].map(i=>Math.pow(parseInt(hex.slice(i,i+2),16)/255,2.2))}
 const vertex=`#version 300 es
 precision highp float;layout(location=0)in vec3 pos;layout(location=1)in vec3 normal;layout(location=2)in vec2 uv;uniform mat4 model,vp,lightVP;out vec3 worldPos;out vec3 N;out vec2 UV;out vec4 shadowPos;void main(){vec4 w=model*vec4(pos,1.);worldPos=w.xyz;N=normalize(transpose(inverse(mat3(model)))*normal);UV=uv;shadowPos=lightVP*w;gl_Position=vp*w;}`;
 const fragment=`#version 300 es
 precision highp float;in vec3 worldPos;in vec3 N;in vec2 UV;in vec4 shadowPos;out vec4 frag;uniform vec3 tint,eye,lightDir;uniform sampler2D tex,shadowTex;uniform float rough,metal,emit,selected,exposure,bumpStrength;uniform vec2 repeatUV;uniform bool shadows;
 float shadow(vec3 nn){if(!shadows)return 1.;vec3 p=shadowPos.xyz/shadowPos.w*.5+.5;if(p.x<0.||p.x>1.||p.y<0.||p.y>1.||p.z>1.)return 1.;float bias=max(.0003,.0011*(1.-dot(nn,lightDir)));float s=0.;vec2 ts=1./vec2(textureSize(shadowTex,0));for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture(shadowTex,p.xy+vec2(x,y)*ts*1.3).r;s+=p.z-bias<=d?1.:0.;}return s/9.;}
 void main(){vec3 nn=normalize(N);if(!gl_FrontFacing)nn=-nn;if(bumpStrength>0.){float h=dot(texture(tex,UV*repeatUV).rgb,vec3(.299,.587,.114));vec3 dx=dFdx(worldPos),dy=dFdy(worldPos),r1=cross(dy,nn),r2=cross(nn,dx);float det=dot(dx,r1);if(abs(det)>.00001)nn=normalize(abs(det)*nn-sign(det)*(dFdx(h)*r1+dFdy(h)*r2)*bumpStrength);}vec3 v=normalize(eye-worldPos),l=normalize(lightDir),hh=normalize(l+v);vec3 albedo=pow(texture(tex,UV*repeatUV).rgb,vec3(2.2))*tint;float nl=max(dot(nn,l),0.),nv=max(dot(nn,v),.001),nh=max(dot(nn,hh),0.),hv=max(dot(hh,v),0.);float a=max(rough*rough,.04),a2=a*a,den=nh*nh*(a2-1.)+1.;float D=a2/(3.141593*den*den);float k=(rough+1.)*(rough+1.)/8.;float G=nv/(nv*(1.-k)+k)*nl/(nl*(1.-k)+k);vec3 F0=mix(vec3(.045),albedo,metal),F=F0+(1.-F0)*pow(1.-hv,5.);vec3 spec=D*G*F/max(4.*nv*nl,.01);vec3 diff=albedo*(1.-metal)/3.141593;float sh=shadow(nn);vec3 direct=(diff+spec)*nl*mix(.13,1.,sh)*vec3(2.65,2.55,2.38);vec3 amb=albedo*mix(vec3(.19,.21,.19),vec3(.50,.57,.59),nn.y*.5+.5)*(1.-metal*.6);vec3 refl=F0*(.25+.35*max(nn.y,0.))*(1.-rough*.6);float rim=pow(1.-nv,3.);vec3 col=direct+amb+refl+albedo*emit+selected*vec3(.1,.33,.24)*(rim+.18);col*=exposure;col=clamp((col*(2.51*col+.03))/(col*(2.43*col+.59)+.14),0.,1.);col=pow(col,vec3(1./2.2));frag=vec4(col,1.);}`;
 const simpleV=`#version 300 es
 layout(location=0)in vec3 pos;uniform mat4 model,vp;void main(){gl_Position=vp*model*vec4(pos,1.);}`;
 const depthF=`#version 300 es
 precision highp float;out vec4 frag;void main(){frag=vec4(1.);}`;
 const pickF=`#version 300 es
 precision highp float;uniform vec3 pickColor;out vec4 frag;void main(){frag=vec4(pickColor,1.);}`;
 class Renderer{
  constructor(canvas){this.canvas=canvas;const gl=this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('WebGL2 indisponível');this.prog=this.program(vertex,fragment);this.depthProg=this.program(simpleV,depthF);this.pickProg=this.program(simpleV,pickF);this.cache=new WeakMap;this.textureCache=new WeakMap;this.root=new Node;this.eye=[7,7,11];this.target=[0,2.5,0];this.fov=40*Math.PI/180;this.shadows=true;this.exposure=.92;this.highlight=0;this.width=1;this.height=1;this.light=[-7,13,9];this.lightDirection=V.norm(this.light);this.lightVP=mul(ortho(-18,18,-14,17,1,70),look(V.mul(this.lightDirection,28),[0,1,0]));this.white=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.white);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([255,255,255,255]));
   this.depthTex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.depthTex);gl.texImage2D(gl.TEXTURE_2D,0,gl.DEPTH_COMPONENT24,2048,2048,0,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT,null);[gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER].forEach(v=>gl.texParameteri(gl.TEXTURE_2D,v,gl.NEAREST));[gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T].forEach(v=>gl.texParameteri(gl.TEXTURE_2D,v,gl.CLAMP_TO_EDGE));this.depthFB=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.depthFB);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,this.depthTex,0);gl.drawBuffers([gl.NONE]);gl.readBuffer(gl.NONE);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)this.shadows=false;gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.pickFB=gl.createFramebuffer();this.pickTex=gl.createTexture();this.pickDepth=gl.createRenderbuffer();gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);this.resize();
  }
  program(v,f){const g=this.gl,p=g.createProgram();[ [g.VERTEX_SHADER,v],[g.FRAGMENT_SHADER,f] ].forEach(([t,s])=>{const sh=g.createShader(t);g.shaderSource(sh,s);g.compileShader(sh);if(!g.getShaderParameter(sh,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(sh));g.attachShader(p,sh)});g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));p.loc={};return p}
  loc(p,k){return p.loc[k]??(p.loc[k]=this.gl.getUniformLocation(p,k))}
  resize(){const g=this.gl,r=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,innerWidth<700?1.35:1.65);this.width=Math.max(1,r.width);this.height=Math.max(1,r.height);let w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(this.canvas.width===w&&this.canvas.height===h&&this.pickAllocated)return;this.pickAllocated=true;this.canvas.width=w;this.canvas.height=h;g.bindTexture(g.TEXTURE_2D,this.pickTex);g.texImage2D(g.TEXTURE_2D,0,g.RGBA8,w,h,0,g.RGBA,g.UNSIGNED_BYTE,null);[g.TEXTURE_MIN_FILTER,g.TEXTURE_MAG_FILTER].forEach(v=>g.texParameteri(g.TEXTURE_2D,v,g.NEAREST));g.bindRenderbuffer(g.RENDERBUFFER,this.pickDepth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT24,w,h);g.bindFramebuffer(g.FRAMEBUFFER,this.pickFB);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.pickTex,0);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,this.pickDepth);g.bindFramebuffer(g.FRAMEBUFFER,null)}
  geometry(d){if(this.cache.has(d))return this.cache.get(d);const g=this.gl,vao=g.createVertexArray();g.bindVertexArray(vao);[d.p,d.n,d.u].forEach((arr,i)=>{const b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,arr,g.STATIC_DRAW);g.enableVertexAttribArray(i);g.vertexAttribPointer(i,i===2?2:3,g.FLOAT,false,0,0)});const b=g.createBuffer();g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,b);g.bufferData(g.ELEMENT_ARRAY_BUFFER,d.idx,g.STATIC_DRAW);const out={vao,count:d.idx.length};this.cache.set(d,out);return out}
  texture(canvas){if(!canvas)return this.white;if(this.textureCache.has(canvas))return this.textureCache.get(canvas);const g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,canvas);g.generateMipmap(g.TEXTURE_2D);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR_MIPMAP_LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.REPEAT);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.REPEAT);this.textureCache.set(canvas,t);return t}
  update(){this.vp=mul(perspective(this.fov,this.width/this.height),look(this.eye,this.target));this.draws=[];const walk=(node,parent,id=0)=>{if(!node.visible)return;node.world=mul(parent,compose(node.p,node.r,node.s));id=node.pickId||id;if(node.geo)this.draws.push({node,id});node.children.forEach(c=>walk(c,node.world,id))};walk(this.root,identity())}
  drawPass(p,shadow=false,pick=false){const g=this.gl;g.useProgram(p);g.uniformMatrix4fv(this.loc(p,'vp'),false,shadow?this.lightVP:this.vp);if(!shadow&&!pick){g.uniformMatrix4fv(this.loc(p,'lightVP'),false,this.lightVP);g.uniform3fv(this.loc(p,'eye'),this.eye);g.uniform3fv(this.loc(p,'lightDir'),this.lightDirection);g.uniform1f(this.loc(p,'exposure'),this.exposure);g.uniform1i(this.loc(p,'shadows'),this.shadows);g.uniform1i(this.loc(p,'tex'),0);g.uniform1i(this.loc(p,'shadowTex'),1);g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,this.depthTex)}for(const {node,id}of this.draws){if(shadow&&!node.cast)continue;const d=this.geometry(node.geo);g.bindVertexArray(d.vao);g.uniformMatrix4fv(this.loc(p,'model'),false,node.world);if(pick)g.uniform3fv(this.loc(p,'pickColor'),[id/255,0,0]);else if(!shadow){const m=node.mat||{};g.uniform3fv(this.loc(p,'tint'),m.linearColor||(m.linearColor=color(m.color||'#ffffff')));g.uniform1f(this.loc(p,'rough'),m.rough??.7);g.uniform1f(this.loc(p,'metal'),m.metal||0);g.uniform1f(this.loc(p,'bumpStrength'),m.bump??(m.texture?.10:0));g.uniform1f(this.loc(p,'emit'),m.emit||0);g.uniform1f(this.loc(p,'selected'),id&&id===this.highlight?1:0);g.uniform2fv(this.loc(p,'repeatUV'),m.repeat||[1,1]);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.texture(m.texture));}g.drawElements(g.TRIANGLES,d.count,g.UNSIGNED_INT,0)}}
  render(){if(this.lost)return;const begun=performance.now();this.resize();this.update();const g=this.gl;if(this.shadows){g.bindFramebuffer(g.FRAMEBUFFER,this.depthFB);g.viewport(0,0,2048,2048);g.clear(g.DEPTH_BUFFER_BIT);g.enable(g.POLYGON_OFFSET_FILL);g.polygonOffset(1.2,2.);this.drawPass(this.depthProg,true);g.disable(g.POLYGON_OFFSET_FILL);}g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(.933,.94,.915,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);this.drawPass(this.prog);this.lastFrameMs=Math.round(performance.now()-begun)}
  pick(x,y){const g=this.gl;this.update();g.bindFramebuffer(g.FRAMEBUFFER,this.pickFB);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(0,0,0,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.disable(g.DITHER);this.drawPass(this.pickProg,false,true);const pixel=new Uint8Array(4);g.readPixels(Math.round(x/this.width*(this.canvas.width-1)),Math.round((1-y/this.height)*(this.canvas.height-1)),1,1,g.RGBA,g.UNSIGNED_BYTE,pixel);g.enable(g.DITHER);g.bindFramebuffer(g.FRAMEBUFFER,null);return pixel[0]}
  project(p){const q=transform(this.vp,p);return{x:(q[0]+1)*.5*this.width,y:(1-q[1])*.5*this.height,visible:V.dot(V.sub(p,this.eye),V.sub(this.target,this.eye))>0&&q[2]>-1&&q[2]<1}}
  worldPoint(node,p=[0,0,0]){return transform(node.world,p)}
  rayOnPlane(x,y,height){const f=V.norm(V.sub(this.target,this.eye)),right=V.norm(V.cross(f,[0,1,0])),up=V.cross(right,f),nx=(x/this.width*2-1)*Math.tan(this.fov/2)*this.width/this.height,ny=(1-y/this.height*2)*Math.tan(this.fov/2),dir=V.norm(V.add(f,V.add(V.mul(right,nx),V.mul(up,ny))));const t=(height-this.eye[1])/dir[1];return t>0?V.add(this.eye,V.mul(dir,t)):null}
 }
 return{Node,Renderer,V,mul,compose,identity,transform,look,perspective,roundedBox,slab,cylinder,sphere,plane,polygon,color};
})();
